### PR TITLE
[#276] Do not allow data transfers to redirect by default

### PR DESCRIPTION
**Pull request by alanking**
Addresses #263
Addresses #276

Added some words to the README about this phenomenon in case that seems helpful.

### CODE REVIEW

**Comment by alanking** [comment]
Something I wanted to mention... The issues observed in #276 were reduced by using the latest release of the python-irodsclient. Should we go ahead and address https://github.com/irods/irods_capability_automated_ingest/issues/263 here as well?

**Comment by korydraughn** [comment]
Are there downsides to addressing #263 now?

**Comment by trel** [comment]
I can't think of any downsides.   Ingest users will be using a virtualenv most probably.   Let's add another commit for #263.

**Comment by korydraughn** [comment]
Agreed. We have tests.

**Comment by alanking** [comment]
Sold. Running tests...

**Comment by alanking** [comment]
Tests passed with PRC 2.1.0 installed.

**Comment by trel** [comment]
nice.

**Review by korydraughn — APPROVED** [review]
Ship it!

**Pull request merged**
