### PR TITLE
[#180] Update requirements.txt

### PR DESCRIPTION
**Pull request by alanking**
This file has not been updated in a while, as you can see. Perhaps we need to start doing this before each release to make sure everything is the right version.

### CODE REVIEW

**Comment by trel** [comment]
do we need to declare all these things?

can/shouldn't we leave the dependencies of dependencies out?   are there any of those?

**Comment by alanking** [comment]
The setup.py file is the thing driving dependencies. 0.6.0 has the following explicit dependencies:
https://github.com/irods/irods_capability_automated_ingest/blob/b96fc67b824e050840eb8f47720bde922b06b936/setup.py#L43-L50

0.6.0 actually uses `os.scandir`, so we don't even need that `scandir` dependency. The rest of these are used directly by the ingest tool.

Everywhere I've seen on the Internet says that this is how you generate a requirements.txt for a project:
```
pip freeze > requirements.txt
```
So, this is what I've done here with a clean environment which simply installed the `irods-capability-automated-ingest` pip package. The `pip freeze` documentation itself employs this practice as well: https://pip.pypa.io/en/stable/cli/pip_freeze/#examples

Willing to try only specifying the direct dependencies, but that does not appear to be standard practice.

**Comment by trel** [comment]
i see - that does make sense.       yes, please try a clean install without `scandir` and... then yes, i think we're good.

thanks.

**Comment by alanking** [comment]
Removed `scandir` dependency from `setup.py`, ran `pip freeze > requirements.txt` again, and tests are running now.

**Comment by alanking** [comment]
Tests passed.

**Comment by trel** [comment]
looks good to me - i think it's ready.

**Comment by alanking** [comment]
Okey dokey. Number go up

**Pull request merged**
