### PR TITLE
black formatter - no functional changes

### PR DESCRIPTION
**Pull request by trel**
has not been tested...

posting for discush

### CODE REVIEW

**Comment by trel** [comment]
@d-w-moore please run this branch through the test framework

**Comment by d-w-moore** [comment]
> @d-w-moore please run this branch through the test framework

Tests passed in this branch. An extra commit was necessary to assert 4.2.11 rather than 4.3.0 of iRODS, as the provider to be tested against.  

So this PR should probably wait to be merged, until after #176 (which includes the equivalent of the above-mentioned irods_version forcing commit.)

**Comment by d-w-moore** [comment]
> @d-w-moore please run this branch through the test framework

Tests passed in https://github.com/d-w-moore/irods_capability_automated_ingest/tree/blackish. An extra commit was necessary to assert 4.2.11 rather than 4.3.0 of iRODS, as the provider to be tested against.  

So this PR should probably wait to be merged, until after #176 (which includes the equivalent of the above-mentioned irods_version forcing commit.)

**Comment by trel** [comment]
Ah, very nice.   One point for black.

**Comment by d-w-moore** [comment]
Next stop, PRC

**Comment by trel** [comment]
#176 was merged 15mo ago - so refreshing/rebasing...

**Comment by trel** [comment]
updated, will need to be tested again.

**Comment by alanking** [comment]
There are currently 7 tests failing on tip of main (sans these changes):
```
FAIL: test_put (irods_capability_automated_ingest.test.test_irods_sync.Test_irods_sync_UnicodeEncodeError.test_put)    
FAIL: test_put_append (irods_capability_automated_ingest.test.test_irods_sync.Test_irods_sync_UnicodeEncodeError.test_put_append)
FAIL: test_put_sync (irods_capability_automated_ingest.test.test_irods_sync.Test_irods_sync_UnicodeEncodeError.test_put_sync)
FAIL: test_register (irods_capability_automated_ingest.test.test_irods_sync.Test_irods_sync_UnicodeEncodeError.test_register)
FAIL: test_update_metadata (irods_capability_automated_ingest.test.test_irods_sync.Test_update_metadata.test_update_metadata)
FAIL: test_update_metadata_root_with_resc_name (irods_capability_automated_ingest.test.test_irods_sync.Test_update_metadata.test_update_metadata_root_with_resc_name)
FAIL: test_update_metadata_with_resc_name (irods_capability_automated_ingest.test.test_irods_sync.Test_update_metadata.test_update_metadata_with_resc_name)
```

**Comment by alanking** [comment]
Happily, the same 7 tests fail with these changes.

**Comment by alanking** [comment]
Let's link this to #180 and get it in.

**Comment by trel** [comment]
done and #'d.

**Review by alanking — APPROVED** [review]

**Pull request merged**
