### PR TITLE
[#299] v0.6.0, plus python version bumps

### PR DESCRIPTION
**Pull request by alanking**
In service of #299 

We can hold on this til the release notes are done.

### CODE REVIEW

**Comment by korydraughn** [comment]
In the commit body: `words captures what` -> `words capture what` ?

**Comment by alanking** [comment]
Fix'd

**Comment by trel** [comment]
looks good.

**Review by korydraughn — APPROVED** [review]
Pound it.

This should be merged before the changelog edits assuming the code is ready for release.

**Comment by alanking** [comment]
#'d. I'll let someone else merge, or, will await the "ready for release" signal.

**Comment by trel** [comment]
one day we'll update this line too...

```
        "Development Status :: 4 - Beta",
```

feel like we're very close.

I think this is done - please to merge when ready.

**Pull request merged**
